// <auto-generated />
using System;
using HienMauNhanDao_DaNang.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HienMauNhanDao_DaNang.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260627061518_InitDB")]
    partial class InitDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HienMauNhanDao_DaNang.Models.Entities.ChiTietNhapXuat", b =>
                {
                    b.Property<string>("MaPhieu")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maPhieu");

                    b.Property<string>("MaTuiMau")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("maTuiMau");

                    b.HasKey("MaPhieu", "MaTuiMau");

                    b.HasIndex("MaTuiMau");

                    b.ToTable("CHITIETNHAPXUAT");
                });

            modelBuilder.Entity("HienMauNhanDao_DaNang.Models.Entities.ChienDichHienMau", b =>
                {
                    b.Property<string>("MaChienDich")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maChienDich");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("imageUrl");

                    b.Property<string>("MaDiaDiem")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maDiaDiem");

                    b.Property<string>("MaNhanVien")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maNhanVien");

                    b.Property<int?>("SoLuongDuKien")
                        .HasColumnType("int")
                        .HasColumnName("soLuongDuKien");

                    b.Property<string>("TenChienDich")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("tenChienDich");

                    b.Property<DateTime>("ThoiGianBD")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("thoiGianBD");

                    b.Property<DateTime>("ThoiGianKT")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("thoiGianKT");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("trangThai");

                    b.HasKey("MaChienDich");

                    b.HasIndex("MaDiaDiem");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("CHIENDICHHIENMAU");
                });

            modelBuilder.Entity("HienMauNhanDao_DaNang.Models.Entities.ChungNhan", b =>
                {
                    b.Property<string>("MaChungNhan")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maChungNhan");

                    b.Property<string>("FilePDF")
                        .HasColumnType("longtext")
                        .HasColumnName("filePDF");

                    b.Property<string>("MaDon")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maDon");

                    b.Property<string>("MaNhanVien")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maNhanVien");

                    b.Property<DateOnly?>("NgayCap")
                        .HasColumnType("date")
                        .HasColumnName("ngayCap");

                    b.HasKey("MaChungNhan");

                    b.HasIndex("MaDon");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("CHUNGNHAN");
                });

            modelBuilder.Entity("HienMauNhanDao_DaNang.Models.Entities.DiaDiem", b =>
                {
                    b.Property<string>("MaDiaDiem")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maDiaDiem");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("diaChi");

                    b.Property<string>("LoaiDiaDiem")
                        .HasColumnType("longtext")
                        .HasColumnName("loaiDiaDiem");

                    b.Property<string>("MaPhuongXa")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maPhuongXa");

                    b.Property<string>("TenDiaDiem")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("tenDiaDiem");

                    b.HasKey("MaDiaDiem");

                    b.HasIndex("MaPhuongXa");

                    b.ToTable("DIADIEM");
                });

            modelBuilder.Entity("HienMauNhanDao_DaNang.Models.Entities.DonDangKy", b =>
                {
                    b.Property<string>("MaDon")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maDon");

                    b.Property<string>("MaChienDich")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maChienDich");

                    b.Property<string>("MaNhanVien")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maNhanVien");

                    b.Property<string>("MaQR")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("maQR");

                    b.Property<string>("MaTNV")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maTNV");

                    b.Property<int?>("TheTich")
                        .HasColumnType("int")
                        .HasColumnName("theTich");

                    b.Property<DateTime?>("ThoiGianDangKy")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("thoiGianDangKy");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("trangThai");

                    b.HasKey("MaDon");

                    b.HasIndex("MaChienDich");

                    b.HasIndex("MaNhanVien");

                    b.HasIndex("MaTNV");

                    b.ToTable("DONDANGKY");
                });

            modelBuilder.Entity("HienMauNhanDao_DaNang.Models.Entities.HoSoSucKhoe", b =>
                {
                    b.Property<string>("MaHoSo")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maHoSo");

                    b.Property<bool?>("CoThai")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("coThai");

                    b.Property<bool?>("DauHong")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("dauHong");

                    b.Property<bool?>("KhangSinh")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("khangSinh");

                    b.Property<string>("MaDon")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maDon");

                    b.Property<string>("MoTaKhac")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("moTaKhac");

                    b.Property<bool?>("TruyenNhiem")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("truyenNhiem");

                    b.HasKey("MaHoSo");

                    b.HasIndex("MaDon");

                    b.ToTable("HOSOSUCKHOE");
                });

            modelBuilder.Entity("HienMauNhanDao_DaNang.Models.Entities.InvalidatedToken", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id");

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expiry_time");

                    b.HasKey("Id");

                    b.ToTable("INVALIDATED_TOKEN");
                });

            modelBuilder.Entity("HienMauNhanDao_DaNang.Models.Entities.KetQuaLamSang", b =>
                {
                    b.Property<string>("MaKQ")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maKQ");

                    b.Property<double?>("CanNang")
                        .HasColumnType("double")
                        .HasColumnName("canNang");

                    b.Property<string>("HuyetAp")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("huyetAp");

                    b.Property<bool?>("KetQua")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ketQua");

                    b.Property<string>("LyDoTuChoi")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("lyDoTuChoi");

                    b.Property<string>("MaDon")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maDon");

                    b.Property<string>("MaNhanVien")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maNhanVien");

                    b.Property<double?>("NhietDo")
                        .HasColumnType("double")
                        .HasColumnName("nhietDo");

                    b.Property<int?>("NhipTim")
                        .HasColumnType("int")
                        .HasColumnName("nhipTim");

                    b.HasKey("MaKQ");

                    b.HasIndex("MaDon");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("KETQUALAMSANG");
                });

            modelBuilder.Entity("HienMauNhanDao_DaNang.Models.Entities.KetQuaXetNghiem", b =>
                {
                    b.Property<string>("MaKQ")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maKQ");

                    b.Property<bool?>("KetQua")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ketQua");

                    b.Property<string>("MaNhanVien")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maNhanVien");

                    b.Property<string>("MaTuiMau")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("maTuiMau");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("moTa");

                    b.Property<string>("NhomMau")
                        .HasColumnType("longtext")
                        .HasColumnName("nhomMau");

                    b.Property<int?>("SoLanXetNghiem")
                        .HasColumnType("int")
                        .HasColumnName("soLanXetNghiem");

                    b.HasKey("MaKQ");

                    b.HasIndex("MaNhanVien");

                    b.HasIndex("MaTuiMau");

                    b.ToTable("KETQUAXETNGHIEM");
                });

            modelBuilder.Entity("HienMauNhanDao_DaNang.Models.Entities.KhoMau", b =>
                {
                    b.Property<string>("MaKho")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maKho");

                    b.Property<string>("MoTa")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("moTa");

                    b.Property<int?>("NguongAnToan")
                        .HasColumnType("int")
                        .HasColumnName("nguongAnToan");

                    b.Property<string>("NhomMau")
                        .HasColumnType("longtext")
                        .HasColumnName("nhomMau");

                    b.Property<int?>("SoLuongTon")
                        .HasColumnType("int")
                        .HasColumnName("soLuongTon");

                    b.Property<string>("TenKho")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("tenKho");

                    b.HasKey("MaKho");

                    b.ToTable("KhoMau");
                });

            modelBuilder.Entity("HienMauNhanDao_DaNang.Models.Entities.KhoaCongTac", b =>
                {
                    b.Property<string>("MaKhoa")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maKhoa");

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("tenKhoa");

                    b.HasKey("MaKhoa");

                    b.ToTable("KhoaCongTac");
                });

            modelBuilder.Entity("HienMauNhanDao_DaNang.Models.Entities.NhanVien", b =>
                {
                    b.Property<string>("MaNhanVien")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maNhanVien");

                    b.Property<string>("Cccd")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("CCCD");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("longtext")
                        .HasColumnName("gioiTinh");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("hoTen");

                    b.Property<string>("MaDiaDiem")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maDiaDiem");

                    b.Property<string>("MaKhoa")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maKhoa");

                    b.Property<string>("MaTaiKhoan")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maTaiKhoan");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("soDienThoai");

                    b.HasKey("MaNhanVien");

                    b.HasIndex("MaDiaDiem");

                    b.HasIndex("MaKhoa");

                    b.HasIndex("MaTaiKhoan");

                    b.ToTable("NHANVIEN");
                });

            modelBuilder.Entity("HienMauNhanDao_DaNang.Models.Entities.PhieuNhapXuat", b =>
                {
                    b.Property<string>("MaPhieu")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maPhieu");

                    b.Property<string>("LoaiPhieu")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("loaiPhieu");

                    b.Property<string>("MaNhanVien")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maNhanVien");

                    b.Property<DateOnly?>("NgayNhapXuat")
                        .HasColumnType("date")
                        .HasColumnName("ngayNhapXuat");

                    b.HasKey("MaPhieu");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("PHIEUNHAPXUAT");
                });

            modelBuilder.Entity("HienMauNhanDao_DaNang.Models.Entities.PhuongXa", b =>
                {
                    b.Property<string>("maPhuongXa")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maPhuongXa");

                    b.Property<string>("tenPhuongXa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("tenPhuongXa");

                    b.Property<string>("tenQuanHuyen")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("tenQuanHuyen");

                    b.Property<string>("tenThanhPho")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("tenThanhPho");

                    b.HasKey("maPhuongXa");

                    b.ToTable("PhuongXa");
                });

            modelBuilder.Entity("HienMauNhanDao_DaNang.Models.Entities.TaiKhoan", b =>
                {
                    b.Property<string>("MaTaiKhoan")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maTaiKhoan");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("MaVaiTro")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maVaiTro");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("matKhau");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("trangThai");

                    b.HasKey("MaTaiKhoan");

                    b.HasIndex("MaVaiTro");

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("HienMauNhanDao_DaNang.Models.Entities.ThongBao", b =>
                {
                    b.Property<string>("MaThongBao")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maThongBao");

                    b.Property<string>("MaTaiKhoanGui")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maTaiKhoanGui");

                    b.Property<string>("MaTaiKhoanNhan")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maTaiKhoanNhan");

                    b.Property<string>("NoiDung")
                        .HasColumnType("longtext")
                        .HasColumnName("noiDung");

                    b.Property<DateTime>("ThoiGianGui")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("thoiGianGui");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("trangThai");

                    b.HasKey("MaThongBao");

                    b.HasIndex("MaTaiKhoanGui");

                    b.HasIndex("MaTaiKhoanNhan");

                    b.ToTable("THONGBAO");
                });

            modelBuilder.Entity("HienMauNhanDao_DaNang.Models.Entities.TinNhan", b =>
                {
                    b.Property<string>("MaTinNhan")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maTinNhan");

                    b.Property<bool>("DaDoc")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("trangThai");

                    b.Property<string>("MaTaiKhoanGui")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maTaiKhoanGui");

                    b.Property<string>("MaTaiKhoanNhan")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maTaiKhoanNhan");

                    b.Property<string>("NoiDung")
                        .HasColumnType("TEXT")
                        .HasColumnName("noiDung");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("thoiGian");

                    b.HasKey("MaTinNhan");

                    b.HasIndex("MaTaiKhoanGui");

                    b.HasIndex("MaTaiKhoanNhan");

                    b.ToTable("TINNHAN");
                });

            modelBuilder.Entity("HienMauNhanDao_DaNang.Models.Entities.TinTuc", b =>
                {
                    b.Property<string>("MaTinTuc")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maTinTuc");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("longtext")
                        .HasColumnName("hinhAnh");

                    b.Property<string>("MaNhanVien")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maNhanVien");

                    b.Property<DateTime>("NgayDang")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngayDang");

                    b.Property<string>("NoiDung")
                        .HasColumnType("LONGTEXT")
                        .HasColumnName("noiDung");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("tieuDe");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("trangThai");

                    b.HasKey("MaTinTuc");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("TINTUC");
                });

            modelBuilder.Entity("HienMauNhanDao_DaNang.Models.Entities.TinhNguyenVien", b =>
                {
                    b.Property<string>("maTNV")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maTNV");

                    b.Property<string>("Cccd")
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("CCCD");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("diaChi");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("longtext")
                        .HasColumnName("gioiTinh");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("hoTen");

                    b.Property<string>("MaPhuongXa")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maPhuongXa");

                    b.Property<string>("MaTaiKhoan")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maTaiKhoan");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date")
                        .HasColumnName("ngaySinh");

                    b.Property<string>("NhomMau")
                        .HasColumnType("longtext")
                        .HasColumnName("nhomMau");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("soDienThoai");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("trangThai");

                    b.HasKey("maTNV");

                    b.HasIndex("MaPhuongXa");

                    b.HasIndex("MaTaiKhoan");

                    b.ToTable("TinhNguyenVien");
                });

            modelBuilder.Entity("HienMauNhanDao_DaNang.Models.Entities.TuiMau", b =>
                {
                    b.Property<string>("MaTuiMau")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("maTuiMau");

                    b.Property<string>("MaDon")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maDon");

                    b.Property<string>("MaKho")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maKho");

                    b.Property<string>("MaNhanVien")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("maNhanVien");

                    b.Property<double?>("NhietDoVanChuyen")
                        .HasColumnType("double")
                        .HasColumnName("nhietDoVanChuyen");

                    b.Property<int?>("TheTich")
                        .HasColumnType("int")
                        .HasColumnName("theTich");

                    b.Property<DateTime?>("ThoiGianLayMau")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("thoiGianLayMau");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("trangThai");

                    b.HasKey("MaTuiMau");

                    b.HasIndex("MaDon");

                    b.HasIndex("MaKho");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("TUIMAU");
                });

            modelBuilder.Entity("HienMauNhanDao_DaNang.Models.Entities.VaiTro", b =>
                {
                    b.Property<string>("maVaiTro")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaVaiTro");

                    b.Property<string>("tenVaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("TenVaiTro");

                    b.HasKey("maVaiTro");

                    b.ToTable("VaiTro");
                });

            modelBuilder.Entity("HienMauNhanDao_DaNang.Models.Entities.ChiTietNhapXuat", b =>
                {
                    b.HasOne("HienMauNhanDao_DaNang.Models.Entities.PhieuNhapXuat", "PhieuNhapXuat")
                        .WithMany("ChiTietPhieu")
                        .HasForeignKey("MaPhieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HienMauNhanDao_DaNang.Models.Entities.TuiMau", "TuiMau")
                        .WithMany()
                        .HasForeignKey("MaTuiMau")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuNhapXuat");

                    b.Navigation("TuiMau");
                });

            modelBuilder.Entity("HienMauNhanDao_DaNang.Models.Entities.ChienDichHienMau", b =>
                {
                    b.HasOne("HienMauNhanDao_DaNang.Models.Entities.DiaDiem", "DiaDiem")
                        .WithMany()
                        .HasForeignKey("MaDiaDiem");

                    b.HasOne("HienMauNhanDao_DaNang.Models.Entities.NhanVien", "NhanVienPhuTrach")
                        .WithMany()
                        .HasForeignKey("MaNhanVien");

                    b.Navigation("DiaDiem");

                    b.Navigation("NhanVienPhuTrach");
                });

            modelBuilder.Entity("HienMauNhanDao_DaNang.Models.Entities.ChungNhan", b =>
                {
                    b.HasOne("HienMauNhanDao_DaNang.Models.Entities.DonDangKy", "DonDangKy")
                        .WithMany()
                        .HasForeignKey("MaDon");

                    b.HasOne("HienMauNhanDao_DaNang.Models.Entities.NhanVien", "NhanVienKy")
                        .WithMany()
                        .HasForeignKey("MaNhanVien");

                    b.Navigation("DonDangKy");

                    b.Navigation("NhanVienKy");
                });

            modelBuilder.Entity("HienMauNhanDao_DaNang.Models.Entities.DiaDiem", b =>
                {
                    b.HasOne("HienMauNhanDao_DaNang.Models.Entities.PhuongXa", "PhuongXa")
                        .WithMany()
                        .HasForeignKey("MaPhuongXa");

                    b.Navigation("PhuongXa");
                });

            modelBuilder.Entity("HienMauNhanDao_DaNang.Models.Entities.DonDangKy", b =>
                {
                    b.HasOne("HienMauNhanDao_DaNang.Models.Entities.ChienDichHienMau", "ChienDich")
                        .WithMany()
                        .HasForeignKey("MaChienDich");

                    b.HasOne("HienMauNhanDao_DaNang.Models.Entities.NhanVien", "NhanVienPhuTrach")
                        .WithMany()
                        .HasForeignKey("MaNhanVien");

                    b.HasOne("HienMauNhanDao_DaNang.Models.Entities.TinhNguyenVien", "TinhNguyenVien")
                        .WithMany()
                        .HasForeignKey("MaTNV");

                    b.Navigation("ChienDich");

                    b.Navigation("NhanVienPhuTrach");

                    b.Navigation("TinhNguyenVien");
                });

            modelBuilder.Entity("HienMauNhanDao_DaNang.Models.Entities.HoSoSucKhoe", b =>
                {
                    b.HasOne("HienMauNhanDao_DaNang.Models.Entities.DonDangKy", "DonDangKy")
                        .WithMany()
                        .HasForeignKey("MaDon");

                    b.Navigation("DonDangKy");
                });

            modelBuilder.Entity("HienMauNhanDao_DaNang.Models.Entities.KetQuaLamSang", b =>
                {
                    b.HasOne("HienMauNhanDao_DaNang.Models.Entities.DonDangKy", "DonDangKy")
                        .WithMany()
                        .HasForeignKey("MaDon");

                    b.HasOne("HienMauNhanDao_DaNang.Models.Entities.NhanVien", "BacSiKham")
                        .WithMany()
                        .HasForeignKey("MaNhanVien");

                    b.Navigation("BacSiKham");

                    b.Navigation("DonDangKy");
                });

            modelBuilder.Entity("HienMauNhanDao_DaNang.Models.Entities.KetQuaXetNghiem", b =>
                {
                    b.HasOne("HienMauNhanDao_DaNang.Models.Entities.NhanVien", "NhanVienXetNghiem")
                        .WithMany()
                        .HasForeignKey("MaNhanVien");

                    b.HasOne("HienMauNhanDao_DaNang.Models.Entities.TuiMau", "TuiMau")
                        .WithMany()
                        .HasForeignKey("MaTuiMau");

                    b.Navigation("NhanVienXetNghiem");

                    b.Navigation("TuiMau");
                });

            modelBuilder.Entity("HienMauNhanDao_DaNang.Models.Entities.NhanVien", b =>
                {
                    b.HasOne("HienMauNhanDao_DaNang.Models.Entities.DiaDiem", "DiaDiem")
                        .WithMany()
                        .HasForeignKey("MaDiaDiem");

                    b.HasOne("HienMauNhanDao_DaNang.Models.Entities.KhoaCongTac", "KhoaCongTac")
                        .WithMany()
                        .HasForeignKey("MaKhoa");

                    b.HasOne("HienMauNhanDao_DaNang.Models.Entities.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("MaTaiKhoan");

                    b.Navigation("DiaDiem");

                    b.Navigation("KhoaCongTac");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("HienMauNhanDao_DaNang.Models.Entities.PhieuNhapXuat", b =>
                {
                    b.HasOne("HienMauNhanDao_DaNang.Models.Entities.NhanVien", "NhanVienThucHien")
                        .WithMany()
                        .HasForeignKey("MaNhanVien");

                    b.Navigation("NhanVienThucHien");
                });

            modelBuilder.Entity("HienMauNhanDao_DaNang.Models.Entities.TaiKhoan", b =>
                {
                    b.HasOne("HienMauNhanDao_DaNang.Models.Entities.VaiTro", "VaiTro")
                        .WithMany()
                        .HasForeignKey("MaVaiTro");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("HienMauNhanDao_DaNang.Models.Entities.ThongBao", b =>
                {
                    b.HasOne("HienMauNhanDao_DaNang.Models.Entities.TaiKhoan", "NguoiGui")
                        .WithMany()
                        .HasForeignKey("MaTaiKhoanGui")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HienMauNhanDao_DaNang.Models.Entities.TaiKhoan", "NguoiNhan")
                        .WithMany()
                        .HasForeignKey("MaTaiKhoanNhan")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("NguoiGui");

                    b.Navigation("NguoiNhan");
                });

            modelBuilder.Entity("HienMauNhanDao_DaNang.Models.Entities.TinNhan", b =>
                {
                    b.HasOne("HienMauNhanDao_DaNang.Models.Entities.TaiKhoan", "NguoiGui")
                        .WithMany()
                        .HasForeignKey("MaTaiKhoanGui")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HienMauNhanDao_DaNang.Models.Entities.TaiKhoan", "NguoiNhan")
                        .WithMany()
                        .HasForeignKey("MaTaiKhoanNhan")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("NguoiGui");

                    b.Navigation("NguoiNhan");
                });

            modelBuilder.Entity("HienMauNhanDao_DaNang.Models.Entities.TinTuc", b =>
                {
                    b.HasOne("HienMauNhanDao_DaNang.Models.Entities.NhanVien", "NguoiDang")
                        .WithMany()
                        .HasForeignKey("MaNhanVien");

                    b.Navigation("NguoiDang");
                });

            modelBuilder.Entity("HienMauNhanDao_DaNang.Models.Entities.TinhNguyenVien", b =>
                {
                    b.HasOne("HienMauNhanDao_DaNang.Models.Entities.PhuongXa", "PhuongXa")
                        .WithMany()
                        .HasForeignKey("MaPhuongXa");

                    b.HasOne("HienMauNhanDao_DaNang.Models.Entities.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("MaTaiKhoan");

                    b.Navigation("PhuongXa");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("HienMauNhanDao_DaNang.Models.Entities.TuiMau", b =>
                {
                    b.HasOne("HienMauNhanDao_DaNang.Models.Entities.DonDangKy", "DonDangKy")
                        .WithMany()
                        .HasForeignKey("MaDon");

                    b.HasOne("HienMauNhanDao_DaNang.Models.Entities.KhoMau", "KhoMau")
                        .WithMany()
                        .HasForeignKey("MaKho");

                    b.HasOne("HienMauNhanDao_DaNang.Models.Entities.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNhanVien");

                    b.Navigation("DonDangKy");

                    b.Navigation("KhoMau");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("HienMauNhanDao_DaNang.Models.Entities.PhieuNhapXuat", b =>
                {
                    b.Navigation("ChiTietPhieu");
                });
#pragma warning restore 612, 618
        }
    }
}
